
name: Setup Python & Install Requirements
description: Checkout, set up Python, install pip dependencies

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.13'
  node-version:
    description: 'Node.js version'
    required: false
    default: '21.7'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      working-directory: ./src/backend
      run: |
        pip install -r requirements.txt

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Node dependencies
      shell: bash
      working-directory: ./src/frontend
      run: |
        npm ci
