# Generated by Django 4.2.20 on 2025-04-02 10:56

import django.db.models.deletion
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("access_requests", "0001_initial"),
        ("barriers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbarrier",
            name="access_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The request from which this access was created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="access_requests.accessrequest",
            ),
        ),
        migrations.AddField(
            model_name="userbarrier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="device_password",
            field=models.CharField(blank=True, help_text="Device password for managing.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="device_phone",
            field=models.CharField(
                db_index=True,
                help_text="Enter a phone number in the format +7XXXXXXXXXX.",
                max_length=20,
                validators=[core.validators.PhoneNumberValidator()],
            ),
        ),
    ]
