# Generated by Django 4.2.20 on 2025-04-09 12:16

from django.db import migrations


def create_limits(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    BarrierLimit = apps.get_model("barriers", "BarrierLimit")

    for barrier in Barrier.objects.filter(limits__isnull=True):
        BarrierLimit.objects.create(barrier=barrier)


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0003_barrierlimit"),
    ]

    operations = [
        migrations.RunPython(create_limits),
    ]
