# Generated by Django 4.2.20 on 2025-04-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_requests", "0001_initial"),
        ("barriers", "0003_barrierlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrierlimit",
            name="global_schedule_phone_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum number of schedule phone numbers allowed in total", null=True
            ),
        ),
        migrations.AddField(
            model_name="barrierlimit",
            name="schedule_interval_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum number of schedule phone numbers allowed in total", null=True
            ),
        ),
        migrations.AddField(
            model_name="barrierlimit",
            name="user_schedule_phone_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum number of schedule phone numbers allowed per user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userbarrier",
            name="access_request",
            field=models.ForeignKey(
                help_text="The request from which this access was created.",
                on_delete=django.db.models.deletion.PROTECT,
                to="access_requests.accessrequest",
            ),
        ),
    ]
