# Generated by Django 4.2.20 on 2025-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0004_barrierlimit_global_schedule_phone_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbarrier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
