# Generated by Django 4.2.20 on 2025-04-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barriers", "0004_barrierlimit_global_schedule_phone_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarrierPhone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Enter a phone number in the format +7XXXXXXXXXX.",
                        max_length=20,
                        validators=[core.validators.PhoneNumberValidator()],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("permanent", "Permanent"),
                            ("temporary", "Temporary"),
                            ("schedule", "Schedule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "device_serial_number",
                    models.PositiveIntegerField(help_text="Index of this phone in the barrier's device memory."),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barrier",
                    models.ForeignKey(
                        help_text="Barrier where this phone number is registered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barrier_phones",
                        to="barriers.barrier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this phone number.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barrier_phones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "barrier_phone",
                "unique_together": {("user", "barrier", "phone")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleInterval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Start time in HH:MM")),
                ("end_time", models.TimeField(help_text="End time in HH:MM")),
                (
                    "phone",
                    models.ForeignKey(
                        help_text="Phone to which this interval belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_intervals",
                        to="phones.barrierphone",
                    ),
                ),
            ],
            options={
                "db_table": "phone_schedule_interval",
                "ordering": ["day", "start_time"],
            },
        ),
    ]
