# Generated by Django 4.2.20 on 2025-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrierphone",
            name="access_state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("error_opening", "Error Opening"),
                    ("error_closing", "Error Closing"),
                ],
                default="unknown",
                help_text="Current access state of the phone.",
                max_length=20,
            ),
        ),
    ]
