# Generated by Django 4.2.20 on 2025-05-15 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_barrierphone_access_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrierphone",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scheduletimeinterval",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduletimeinterval",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
