# Generated by Django 4.2.20 on 2025-04-26 15:01

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Enter a phone number in the format +7XXXXXXXXXX.",
                        max_length=20,
                        validators=[core.validators.PhoneNumberValidator()],
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification Code"),
                            ("phone_command", "Phone Command"),
                            ("barrier_setting", "Barrier Setting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Waiting for sending"),
                            ("sent", "Sent"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sms_message",
            },
        ),
    ]
