# Generated by Django 4.2.20 on 2025-05-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_history", "0001_initial"),
        ("message_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsmessage",
            name="metadata",
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="action",
            field=models.ForeignKey(
                blank=True,
                help_text="Action that triggered this message, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sms_messages",
                to="action_history.actionhistory",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="command_type",
            field=models.CharField(
                blank=True, choices=[("open", "Open Access"), ("close", "Close Access")], max_length=20, null=True
            ),
        ),
    ]
