# Generated by Django 4.2.20 on 2025-05-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_history", "0002_barrieractionlog_remove_actionhistory_barrier_and_more"),
        ("message_management", "0002_remove_smsmessage_metadata_smsmessage_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsmessage",
            name="action",
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="log",
            field=models.ForeignKey(
                blank=True,
                help_text="Action that triggered this message, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sms_messages",
                to="action_history.barrieractionlog",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
