# Generated by Django 4.2.20 on 2025-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_management", "0003_remove_smsmessage_action_smsmessage_log_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smsmessage",
            old_name="command_type",
            new_name="phone_command_type",
        ),
        migrations.RemoveField(
            model_name="smsmessage",
            name="response_payload",
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="failure_reason",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="response_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
