# Generated by Django 4.2.20 on 2025-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_management", "0004_rename_command_type_smsmessage_phone_command_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("verification", "Verification Code"),
                    ("phone_command", "Phone Command"),
                    ("barrier_setting", "Barrier Setting"),
                    ("balance_check", "Balance Check"),
                ],
                max_length=20,
            ),
        ),
    ]
