# Generated by Django 4.2.20 on 2025-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_management", "0005_alter_smsmessage_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
