# Generated by Django 4.2.20 on 2025-03-31 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barriers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "request_type",
                    models.CharField(
                        choices=[("from_user", "From user"), ("from_barrier", "From barrier")],
                        help_text="Direction of the access request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the access request",
                        max_length=20,
                    ),
                ),
                ("hidden_for_user", models.BooleanField(default=False)),
                ("hidden_for_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "barrier",
                    models.ForeignKey(
                        help_text="Barrier to which access is requested.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_requests",
                        to="barriers.barrier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requests access.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "access_request",
            },
        ),
    ]
