apiVersion: 1

datasources:
  - name: Loki
    uid: loki-ds
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFieldsEnabled: false
      disableLabelBrowser: true
      disableLogFieldLineLabels: true
      disableLogFieldValueSuggestions: true
