services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: django_backend
    working_dir: /backend_app
    env_file:
      - backend/prod.env
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./backend/staticfiles:/backend_app/staticfiles
      - ./backend/logs:/backend_app/logs
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1" ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - backend/prod.env
    command: >
      postgres
      -c log_timezone=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: react_frontend
    working_dir: /frontend_app
    env_file:
      - frontend/prod.env
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4173/ || exit 1" ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      kafka-ui:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
      - ./backend/staticfiles:/backend_app/staticfiles
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -fs http://localhost/ && \
           curl -fs http://localhost/admin_panel/ && \
           curl -fs http://localhost/api/health/ && \
           curl -fs http://localhost/kafka_ui/ || exit 1"
      ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - kafka/kafka.env
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

  kafka-init:
    image: bitnami/kafka:3.9.0
    container_name: kafka-init
    env_file:
      - kafka/kafka.env
    entrypoint: [ "/bin/bash", "-c", "/init_topics.sh" ]
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./kafka/init_topics.sh:/init_topics.sh


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    env_file:
      - kafka/kafka-ui.env
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080" ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  kafka_data:
