services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: django_backend
    working_dir: /backend_app
    volumes:
      - ./backend:/backend_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: react_frontend
    working_dir: /frontend_app
    volumes:
      - ./frontend:/frontend_app
      - /frontend_app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - frontend/.env

volumes:
  postgres_data: