services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: django_backend
    working_dir: /backend_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/prod.env
    volumes:
      - ./backend/staticfiles:/backend_app/staticfiles
      - ./backend/logs:/backend_app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - backend/prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: react_frontend
    working_dir: /frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - frontend/prod.env
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/backend_app/staticfiles

volumes:
  postgres_data:
