# Generated by Django 4.2.20 on 2025-05-07 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phones", "0002_barrierphone_access_state"),
        ("barriers", "0004_barrierlimit_global_schedule_phone_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "author",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin"), ("system", "System")], max_length=20
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add_phone", "Add Phone"),
                            ("delete_phone", "Delete Phone"),
                            ("update_phone", "Update Phone"),
                            ("barrier_setting", "Barrier Setting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Action"),
                            ("barrier_exit", "User Left Barrier or Admin deleted user from barrier"),
                            ("access_granted", "Access Granted"),
                            ("primary_phone_change", "Primary Phone Changed"),
                            ("schedule_update", "Schedule Updated"),
                            ("time_update", "Temporary Time Updated"),
                            ("end_time", "Deleting phone after its time ended"),
                            ("barrier_deleted", "Barrier Deleted"),
                            ("user_deleted", "User Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_data", models.JSONField(blank=True, help_text="Initial request data", null=True)),
                ("message", models.TextField(blank=True, default="", help_text="Human-readable message or logs")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "barrier",
                    models.ForeignKey(
                        help_text="Barrier associated with the action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_histories",
                        to="barriers.barrier",
                    ),
                ),
                (
                    "phone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Phone involved in the action, if any",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_histories",
                        to="phones.barrierphone",
                    ),
                ),
            ],
            options={
                "db_table": "action_history",
                "indexes": [
                    models.Index(fields=["created_at", "phone", "barrier"], name="action_hist_created_bcb6d9_idx")
                ],
            },
        ),
    ]
