# Generated by Django 4.2.20 on 2025-05-07 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarrierActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "author",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin"), ("system", "System")], max_length=20
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add_phone", "Add Phone"),
                            ("delete_phone", "Delete Phone"),
                            ("update_phone", "Update Phone"),
                            ("barrier_setting", "Barrier Setting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Action"),
                            ("barrier_exit", "User Left Barrier or Admin deleted user from barrier"),
                            ("access_granted", "Access Granted"),
                            ("primary_phone_change", "Primary Phone Changed"),
                            ("schedule_update", "Schedule Updated"),
                            ("end_time", "Deleting phone after its time ended"),
                            ("barrier_deleted", "Barrier Deleted"),
                            ("user_deleted", "User Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="String representation of the previous value/state.", null=True
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="String representation of the new value/state.", null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "barrier_action_log",
            },
        ),
        migrations.RemoveField(
            model_name="actionhistory",
            name="barrier",
        ),
        migrations.RemoveField(
            model_name="actionhistory",
            name="phone",
        ),
    ]
