# Generated by Django 4.2.20 on 2025-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_history", "0003_delete_actionhistory_barrieractionlog_barrier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrieractionlog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Action"),
                    ("access_granted", "Access Granted"),
                    ("primary_phone_change", "Primary Phone Changed"),
                    ("schedule_update", "Schedule Updated"),
                    ("end_time", "Deleting phone after its time ended"),
                    ("barrier_exit", "User Left Barrier or Admin deleted user from barrier"),
                    ("barrier_deleted", "Barrier Deleted"),
                    ("user_deleted", "User Deleted"),
                ],
                max_length=20,
            ),
        ),
    ]
