name: Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linters:
    name: Code Style & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Black
        working-directory: ./src/backend
        run: black . --check --diff

      - name: Run isort
        working-directory: ./src/backend
        run: isort . --check --diff

      - name: Run Ruff
        working-directory: ./src/backend
        run: ruff check . --output-format=github

  backend-tests:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run pytest
        working-directory: ./src/backend
        run: pytest -v

  validate-migrations:
    name: Check Django Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check for pending migrations
        working-directory: ./src/backend
        run: |
          python manage.py makemigrations --check --dry-run

  apply-migrations:
    name: Check Django migrate (SQLite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Apply migrations using SQLite
        working-directory: ./src/backend
        run: python manage.py migrate --noinput

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run frontend tests
        working-directory: ./src/frontend
        run: npm test -- --ci --watchAll=false

  frontend-format:
    name: Frontend Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check Prettier formatting
        working-directory: ./src/frontend
        run: npx prettier --check .
