# Generated by Django 4.2.20 on 2025-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_blocked_user_block_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=True, help_text="Designates whether this user should be treated as blocked."
            ),
        ),
    ]
